title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs


title: Distributed Systems with .NET
email: dylan@ursatile.com
description: >- # this means to ignore newlines until "baseurl:"
  Material and code samples for Dylan Beattie's workshop "Distributed Systems with .NET"
baseurl: "/dsnet2025" # the subpath of your site, e.g. /blog
url: "https://ursatile.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ursatile
github_username:  ursatile

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .git
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - node_modules/
  - examples/jstris/node_modules/
  - examples/unit-testing/counter-with-tests/node_modules/
  - examples/advanced-stylesheets/counter/node_modules/
  - examples/snowpack/counter/node_modules/
